<?php
/**
 * MeasurementSet
 *
 * PHP version 5
 *
 * @category Class
 * @package  CureDAO\Client
 * @author   Mike P. Sinn
 * @link     https://github.com/cure-dao
 */

/**

 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and SDKs](https://github.com/cure-dao) or [contact us](https://curedao.org/discord).
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/cure-dao.git
 * Swagger Codegen version: 2.4.9
 */



namespace CureDAO\Client\Model;

use ArrayAccess;
use CureDAO\Client\ObjectSerializer;
use CureDAO\Client\VariableCategories\PhysicalActivityVariableCategory;
use CureDAO\Client\Variables\BaseVariable;

/**
 * MeasurementSet Class Doc Comment
 *
 * @category Class
 * @package  CureDAO\Client
 * @author   Mike P. Sinn
 * @link     https://github.com/cure-dao
 */
class MeasurementSet implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MeasurementSet';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'combination_operation' => 'string',
        'measurement_items' => '\CureDAO\Client\Model\MeasurementItem[]',
        'source_name' => 'string',
        'unit_name' => 'string',
        'variable_category_name' => 'string',
        'variable_name' => 'string',
        'upc' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'combination_operation' => null,
        'measurement_items' => null,
        'source_name' => null,
        'unit_name' => null,
        'variable_category_name' => null,
        'variable_name' => null,
        'upc' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes(): array
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats(): array
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'combination_operation' => 'combinationOperation',
        'measurement_items' => 'measurementItems',
        'source_name' => 'sourceName',
        'unit_name' => 'UnitName',
        'variable_category_name' => 'variableCategoryName',
        'variable_name' => 'variableName',
        'upc' => 'upc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'combination_operation' => 'setCombinationOperation',
        'measurement_items' => 'setMeasurementItems',
        'source_name' => 'setSourceName',
        'unit_name' => 'setUnitName',
        'variable_category_name' => 'setVariableCategoryName',
        'variable_name' => 'setVariableName',
        'upc' => 'setUpc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'combination_operation' => 'getCombinationOperation',
        'measurement_items' => 'getMeasurementItems',
        'source_name' => 'getSourceName',
        'unit_name' => 'getUnitName',
        'variable_category_name' => 'getVariableCategoryName',
        'variable_name' => 'getVariableName',
        'upc' => 'getUpc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$swaggerModelName;
    }

    const COMBINATION_OPERATION_MEAN = 'MEAN';
    const COMBINATION_OPERATION_SUM = 'SUM';
    const VARIABLE_CATEGORY_NAME_ACTIVITY = 'Activity';
    const VARIABLE_CATEGORY_NAME_BOOKS = 'Books';
    const VARIABLE_CATEGORY_NAME_CAUSES_OF_ILLNESS = 'Causes of Illness';
    const VARIABLE_CATEGORY_NAME_COGNITIVE_PERFORMANCE = 'Cognitive Performance';
    const VARIABLE_CATEGORY_NAME_CONDITIONS = 'Conditions';
    const VARIABLE_CATEGORY_NAME_EMOTIONS = 'Emotions';
    const VARIABLE_CATEGORY_NAME_ENVIRONMENT = 'Environment';
    const VARIABLE_CATEGORY_NAME_FOODS = 'Foods';
    const VARIABLE_CATEGORY_NAME_GOALS = 'Goals';
    const VARIABLE_CATEGORY_NAME_LOCATIONS = 'Locations';
    const VARIABLE_CATEGORY_NAME_MISCELLANEOUS = 'Miscellaneous';
    const VARIABLE_CATEGORY_NAME_MOVIES_AND_TV = 'Movies and TV';
    const VARIABLE_CATEGORY_NAME_MUSIC = 'Music';
    const VARIABLE_CATEGORY_NAME_NUTRIENTS = 'Nutrients';
    const VARIABLE_CATEGORY_NAME_PAYMENTS = 'Payments';
    const VARIABLE_CATEGORY_NAME_PHYSICAL_ACTIVITIES = 'Physical Activities';
    const VARIABLE_CATEGORY_NAME_PHYSIQUE = 'Physique';
    const VARIABLE_CATEGORY_NAME_SLEEP = 'Sleep';
    const VARIABLE_CATEGORY_NAME_SOCIAL_INTERACTIONS = 'Social Interactions';
    const VARIABLE_CATEGORY_NAME_SOFTWARE = 'Software';
    const VARIABLE_CATEGORY_NAME_SYMPTOMS = 'Symptoms';
    const VARIABLE_CATEGORY_NAME_TREATMENTS = 'Treatments';
    const VARIABLE_CATEGORY_NAME_VITAL_SIGNS = 'Vital Signs';



    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCombinationOperationAllowableValues(): array
    {
        return [
            self::COMBINATION_OPERATION_MEAN,
            self::COMBINATION_OPERATION_SUM,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVariableCategoryNameAllowableValues(): array
    {
        return [
            self::VARIABLE_CATEGORY_NAME_ACTIVITY,
            self::VARIABLE_CATEGORY_NAME_BOOKS,
            self::VARIABLE_CATEGORY_NAME_CAUSES_OF_ILLNESS,
            self::VARIABLE_CATEGORY_NAME_COGNITIVE_PERFORMANCE,
            self::VARIABLE_CATEGORY_NAME_CONDITIONS,
            self::VARIABLE_CATEGORY_NAME_EMOTIONS,
            self::VARIABLE_CATEGORY_NAME_ENVIRONMENT,
            self::VARIABLE_CATEGORY_NAME_FOODS,
            self::VARIABLE_CATEGORY_NAME_GOALS,
            self::VARIABLE_CATEGORY_NAME_LOCATIONS,
            self::VARIABLE_CATEGORY_NAME_MISCELLANEOUS,
            self::VARIABLE_CATEGORY_NAME_MOVIES_AND_TV,
            self::VARIABLE_CATEGORY_NAME_MUSIC,
            self::VARIABLE_CATEGORY_NAME_NUTRIENTS,
            self::VARIABLE_CATEGORY_NAME_PAYMENTS,
            self::VARIABLE_CATEGORY_NAME_PHYSICAL_ACTIVITIES,
            self::VARIABLE_CATEGORY_NAME_PHYSIQUE,
            self::VARIABLE_CATEGORY_NAME_SLEEP,
            self::VARIABLE_CATEGORY_NAME_SOCIAL_INTERACTIONS,
            self::VARIABLE_CATEGORY_NAME_SOFTWARE,
            self::VARIABLE_CATEGORY_NAME_SYMPTOMS,
            self::VARIABLE_CATEGORY_NAME_TREATMENTS,
            self::VARIABLE_CATEGORY_NAME_VITAL_SIGNS,
            PhysicalActivityVariableCategory::NAME,
        ];
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['combination_operation'] = $data['combination_operation'] ?? null;
        $this->container['measurement_items'] = $data['measurement_items'] ?? null;
        $this->container['source_name'] = $data['source_name'] ?? null;
        $this->container['unit_name'] = $data['unit_name'] ?? null;
        $this->container['variable_category_name'] = $data['variable_category_name'] ?? null;
        $this->container['variable_name'] = $data['variable_name'] ?? null;
        $this->container['upc'] = $data['upc'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        $allowedValues = $this->getCombinationOperationAllowableValues();
        if (!is_null($this->container['combination_operation']) && !in_array($this->container['combination_operation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'combination_operation', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['measurement_items'] === null) {
            $invalidProperties[] = "'measurement_items' can't be null";
        }
        if ($this->container['source_name'] === null) {
            $invalidProperties[] = "'source_name' can't be null";
        }
        if ($this->container['unit_name'] === null) {
            $invalidProperties[] = "'unit_name' can't be null";
        }
        $allowedValues = $this->getVariableCategoryNameAllowableValues();
        if (!is_null($this->container['variable_category_name']) && !in_array($this->container['variable_category_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'variable_category_name', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['variable_name'] === null) {
            $invalidProperties[] = "'variable_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets combination_operation
     *
     * @return string
     */
    public function getCombinationOperation(): string
    {
        return $this->container['combination_operation'];
    }

    /**
     * Sets combination_operation
     *
     * @param string $combination_operation Way to aggregate measurements over time. SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED.
     *
     * @return $this
     */
    public function setCombinationOperation(string $combination_operation): MeasurementSet
    {
        $allowedValues = $this->getCombinationOperationAllowableValues();
        if (!is_null($combination_operation) && !in_array($combination_operation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'combination_operation', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['combination_operation'] = $combination_operation;

        return $this;
    }

    /**
     * Gets measurement_items
     *
     * @return \CureDAO\Client\Model\MeasurementItem[]
     */
    public function getMeasurementItems(): array
    {
        return $this->container['measurement_items'];
    }

    /**
     * Sets measurement_items
     *
     * @param \CureDAO\Client\Model\MeasurementItem[] $measurement_items Array of timestamps, values, and optional notes
     *
     * @return $this
     */
    public function setMeasurementItems(array $measurement_items): MeasurementSet
    {
        $this->container['measurement_items'] = $measurement_items;

        return $this;
    }

    /**
     * Gets source_name
     *
     * @return string
     */
    public function getSourceName(): string
    {
        return $this->container['source_name'];
    }

    /**
     * Sets source_name
     *
     * @param string $source_name Name of the application or device used to record the measurement values
     *
     * @return $this
     */
    public function setSourceName(string $source_name): MeasurementSet
    {
        $this->container['source_name'] = $source_name;

        return $this;
    }

    /**
     * Gets unit_name
     *
     * @return string
     */
    public function getUnitName(): string
    {
        return $this->container['unit_name'];
    }

    /**
     * Sets unit_name
     *
     * @param string $unit_name Unit of measurement
     *
     * @return $this
     */
    public function setUnitName(string $unit_name): MeasurementSet
    {
        $this->container['unit_name'] = $unit_name;

        return $this;
    }

    /**
     * Gets variable_category_name
     *
     * @return string
     */
    public function getVariableCategoryName(): string
    {
        return $this->container['variable_category_name'];
    }

    /**
     * Sets variable_category_name
     *
     * @param string $variable_category_name Ex: Emotions, Treatments, Symptoms...
     *
     * @return $this
     */
    public function setVariableCategoryName(string $variable_category_name): MeasurementSet
    {
        $allowedValues = $this->getVariableCategoryNameAllowableValues();
        if (!in_array($variable_category_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'variable_category_name', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['variable_category_name'] = $variable_category_name;

        return $this;
    }

    /**
     * Gets variable_name
     *
     * @return string
     */
    public function getVariableName(): string
    {
        return $this->container['variable_name'];
    }

    /**
     * Sets variable_name
     *
     * @param string $variable_name ORIGINAL name of the variable for which we are creating the measurement records
     *
     * @return $this
     */
    public function setVariableName(string $variable_name): MeasurementSet
    {
        $this->container['variable_name'] = $variable_name;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc(): string
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc UPC or other barcode scan result
     *
     * @return $this
     */
    public function setUpc(string $upc): MeasurementSet
    {
        $this->container['upc'] = $upc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    public function addMeasurement(float $value, string $startAt, string $endAt = null, string $note = null): MeasurementSet
    {
        $this->container['measurement_items'][] = [
            'value' => $value,
            'start_at' => $startAt,
            'end_at' => $endAt,
            'note' => $note
        ];

        return $this;
    }

    public function addMeasurements(array $valuesAndTimes): MeasurementSet
    {
        foreach ($valuesAndTimes as $valueAndTime) {
            $this->addMeasurement(
                $valueAndTime['value'],
                $valueAndTime['start_at'],
                $valueAndTime['end_at'] ?? null,
                $valueAndTime['note'] ?? null
            );
        }

        return $this;
    }

    public function setVariable(BaseVariable $variable): MeasurementSet
    {
        $this->setVariableName($variable->getName());
        $this->setUnitName($variable->getDefaultUnit()->getName());
        $this->setVariableCategoryName($variable->getVariableCategory()->getName());
        return $this;
    }
    public function toArray(): array
    {
        return $this->container;
    }

}


