<?php
namespace CureDAO\Client\VariableCategories;
use CureDAO\Client\Properties\VariableCategory\VariableCategoryValenceProperty;
use CureDAO\Client\UI\ImageUrls;
use CureDAO\Client\Properties\VariableCategory\BaseFillingTypeProperty;
use CureDAO\Client\Units\OneToFiveRatingUnit;
use CureDAO\Client\Properties\VariableCategory\VariableCategoryCombinationOperationProperty;
use CureDAO\Client\UI\FontAwesome;
use CureDAO\Client\VariableCategories\BaseVariableCategory;
class EmotionsVariableCategory extends BaseVariableCategory {
	const WP_POST_ID = null;
	const UPDATED_AT = '2021-02-06 19:32:42';
	const SORT_ORDER = 0;
	const NUMBER_OF_VARIABLES = 2028;
	const NUMBER_OF_USER_VARIABLES = 43085;
	const NUMBER_OF_PREDICTOR_POPULATION_STUDIES = 41770;
	const NUMBER_OF_PREDICTOR_CASE_STUDIES = 101580;
	const NUMBER_OF_OUTCOME_POPULATION_STUDIES = 5394;
	const NUMBER_OF_OUTCOME_CASE_STUDIES = 17690;
	const NUMBER_OF_MEASUREMENTS = 1211325;
	const NAME_SINGULAR = 'Emotion';
	const MEDIAN_SECONDS_BETWEEN_MEASUREMENTS = null;
	const IS_PUBLIC = true;
	const IS_GOAL = true;
	const DELETED_AT = null;
	const CREATED_AT = '2020-07-28 17:56:03';
	const CONTROLLABLE = false;
	const AVERAGE_SECONDS_BETWEEN_MEASUREMENTS = null;
	const AMAZON_PRODUCT_CATEGORY = null;
	const APP_TYPE = 'mood';
	const BORING = false;
	const CAUSE_ONLY = false;
	const COMBINATION_OPERATION = VariableCategoryCombinationOperationProperty::COMBINATION_MEAN;
	const COMMON = true;
	const DEFAULT_UNIT_ABBREVIATED_NAME = '/5';
	const DEFAULT_UNIT_ID = OneToFiveRatingUnit::ID;
	const DURATION_OF_ACTION = 86400;
	const EFFECT_ONLY = null;
	const FILLING_TYPE = BaseFillingTypeProperty::FILLING_TYPE_NONE;
	const FILLING_VALUE = -1;
	const HELP_TEXT = 'What emotion do you want to rate?';
	const FONT_AWESOME = FontAwesome::GRIN_TONGUE_WINK;
	const ID = 1;
	const IMAGE_URL = ImageUrls::THEATRE_MASK_96_PNG;
	const ION_ICON = 'ion-happy-outline';
	const MANUAL_TRACKING = true;
	const MAXIMUM_ALLOWED_VALUE = null;
	const MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE = 'rating';
	const MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS = 60;
	const MINIMUM_ALLOWED_VALUE = null;
	const MORE_INFO = 'Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.';
	const NAME = 'Emotions';
	const ONSET_DELAY = 0;
	const OUTCOME = true;
	const PNG_PATH = 'img/variable_categories/emotions.png';
    const PNG_URL = 'https://static.quantimo.do/img/variable_categories/emotions.png';
	const PREDICTOR = false;
	const PUBLIC = true;
	const SETUP_QUESTION = 'What is an unpleasant emotion like guiltiness, irritability, or nervousness you experience regularly?';
	const STUDY_IMAGE_FILE_NAME = null;
	const SUFFIX = null;
	const SVG_PATH = 'img/variable_categories/emotions.svg';
    const SVG_URL = 'https://static.quantimo.do/img/variable_categories/emotions.svg';
	const SYNONYMS = ['Emotions', 'Emotion', 'Mood'];
	const VALENCE = VariableCategoryValenceProperty::VALENCE_NEUTRAL;
	const VARIABLE_CATEGORY_NAME = 'Emotions';
	const VARIABLE_CATEGORY_NAME_SINGULAR = 'Emotion';
    public $amazonProductCategory = self::AMAZON_PRODUCT_CATEGORY;
	public $appType = self::APP_TYPE;
	public $boring = self::BORING;
	public $causeOnly = self::CAUSE_ONLY;
	public $combinationOperation = self::COMBINATION_OPERATION;
	public $common = self::COMMON;
	public $defaultUnitAbbreviatedName = self::DEFAULT_UNIT_ABBREVIATED_NAME;
	public $defaultUnitId = self::DEFAULT_UNIT_ID;
	public $durationOfAction = self::DURATION_OF_ACTION;
	public $effectOnly = self::EFFECT_ONLY;
	public $fillingType = self::FILLING_TYPE;
	public $fillingValue = self::FILLING_VALUE;
	public $helpText = self::HELP_TEXT;
	public $fontAwesome = self::FONT_AWESOME;
	public $id = self::ID;
	public $imageUrl = self::IMAGE_URL;
	public $ionIcon = self::ION_ICON;
	public $manualTracking = self::MANUAL_TRACKING;
	public $maximumAllowedValue = self::MAXIMUM_ALLOWED_VALUE;
	public $measurementSynonymSingularLowercase = self::MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE;
	public $minimumAllowedSecondsBetweenMeasurements = self::MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS;
	public $minimumAllowedValue = self::MINIMUM_ALLOWED_VALUE;
	public $moreInfo = self::MORE_INFO;
	public $name = self::NAME;
	public $onsetDelay = self::ONSET_DELAY;
	public $outcome = self::OUTCOME;
	public $pngPath = self::PNG_PATH;
	public $pngUrl = self::PNG_URL;
	public $predictor = self::PREDICTOR;
	public $public = self::PUBLIC;
	public $setupQuestion = self::SETUP_QUESTION;
	public $studyImageFileName = self::STUDY_IMAGE_FILE_NAME;
	public $suffix = self::SUFFIX;
	public $svgPath = self::SVG_PATH;
	public $svgUrl = self::SVG_URL;
	public $synonyms = self::SYNONYMS;
	public $valence = self::VALENCE;
	public $variableCategoryName = self::VARIABLE_CATEGORY_NAME;
	public $variableCategoryNameSingular = self::VARIABLE_CATEGORY_NAME_SINGULAR;
}
