<?php
namespace CureDAO\Client\VariableCategories;
use CureDAO\Client\Properties\Base\BaseFillingTypeProperty;
use CureDAO\Client\Properties\VariableCategory\VariableCategoryNameProperty;
use CureDAO\Client\UI\FontAwesome;
use CureDAO\Client\VariableCategories\BaseVariableCategory;
class FoodsVariableCategory extends BaseVariableCategory {
	const AMAZON_PRODUCT_CATEGORY = 'GourmetFood';
	const APP_TYPE = 'diet';
	const BORING = null;
	const CAUSE_ONLY = true;
	const COMBINATION_OPERATION = 'SUM';
	const COMMON = true;
	const DEFAULT_UNIT_ABBREVIATED_NAME = 'serving';
	const DEFAULT_UNIT_ID = 44;
	const DURATION_OF_ACTION = 864000; // 10 days
	const EFFECT_ONLY = null;
    const FILLING_TYPE = BaseFillingTypeProperty::FILLING_TYPE_ZERO;
    const FILLING_VALUE = 0;
	const HELP_TEXT = 'What did you eat?';
	const FONT_AWESOME = FontAwesome::UTENSILS_SOLID;
	const ID = 15;
    const IMAGE_URL = 'https://static.quantimo.do/img/variable_categories/vegetarian_food-96.png';
	const ION_ICON = 'ion-fork';
	const MANUAL_TRACKING = true;
	const MAXIMUM_ALLOWED_VALUE = null;
	const MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE = 'meal';
	const MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS = null;
	const MINIMUM_ALLOWED_VALUE = 0;
	const MORE_INFO = 'Diet can have a significant impact on your health. It\'s important to enter any foods that you regularly eat to see how they might be affecting you.';
	const NAME = 'Foods';
	const ONSET_DELAY = 1800;
	const OUTCOME = false;
	const PNG_PATH = 'img/variable_categories/foods.png';
    const PNG_URL = 'https://static.quantimo.do/img/variable_categories/foods.png';
	const PREDICTOR = true;
	const PUBLIC = true;
	const SETUP_QUESTION = 'What is a food or drink that you consume more than a few times a week?';
	const STUDY_IMAGE_FILE_NAME = null;
	const SUFFIX = VariableCategoryNameProperty::SUFFIX_INTAKE;
	const SVG_PATH = 'img/variable_categories/foods.svg';
    const SVG_URL = 'https://static.quantimo.do/img/variable_categories/foods.svg';
	const SYNONYMS = ['Grocery', 'Foods', 'Food', 'GourmetFood'];
	const VALENCE = null;
	const VARIABLE_CATEGORY_NAME = 'Foods';
	const VARIABLE_CATEGORY_NAME_SINGULAR = 'Food';
    public $amazonProductCategory = self::AMAZON_PRODUCT_CATEGORY;
	public $appType = self::APP_TYPE;
	public $boring = self::BORING;
	public $causeOnly = self::CAUSE_ONLY;
	public $combinationOperation = self::COMBINATION_OPERATION;
	public $common = self::COMMON;
	public $defaultUnitAbbreviatedName = self::DEFAULT_UNIT_ABBREVIATED_NAME;
	public $defaultUnitId = self::DEFAULT_UNIT_ID;
	public $durationOfAction = self::DURATION_OF_ACTION;
	public $effectOnly = self::EFFECT_ONLY;
	public $fillingType = self::FILLING_TYPE;
	public $fillingValue = self::FILLING_VALUE;
	public $helpText = self::HELP_TEXT;
	public $fontAwesome = self::FONT_AWESOME;
	public $id = self::ID;
	public $imageUrl = self::IMAGE_URL;
	public $ionIcon = self::ION_ICON;
	public $manualTracking = self::MANUAL_TRACKING;
	public $maximumAllowedValue = self::MAXIMUM_ALLOWED_VALUE;
	public $measurementSynonymSingularLowercase = self::MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE;
	public $minimumAllowedSecondsBetweenMeasurements = self::MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS;
	public $minimumAllowedValue = self::MINIMUM_ALLOWED_VALUE;
	public $moreInfo = self::MORE_INFO;
	public $name = self::NAME;
	public $onsetDelay = self::ONSET_DELAY;
	public $outcome = self::OUTCOME;
	public $pngPath = self::PNG_PATH;
	public $pngUrl = self::PNG_URL;
	public $predictor = self::PREDICTOR;
	public $public = self::PUBLIC;
	public $setupQuestion = self::SETUP_QUESTION;
	public $studyImageFileName = self::STUDY_IMAGE_FILE_NAME;
	public $suffix = self::SUFFIX;
	public $svgPath = self::SVG_PATH;
	public $svgUrl = self::SVG_URL;
	public $synonyms = self::SYNONYMS;
	public $valence = self::VALENCE;
	public $variableCategoryName = self::VARIABLE_CATEGORY_NAME;
	public $variableCategoryNameSingular = self::VARIABLE_CATEGORY_NAME_SINGULAR;
}
