<?php
namespace CureDAO\Client\VariableCategories;
use CureDAO\Client\Properties\Base\BaseFillingTypeProperty;
use CureDAO\Client\Properties\VariableCategory\VariableCategoryNameProperty;
use CureDAO\Client\UI\FontAwesome;
use CureDAO\Client\VariableCategories\BaseVariableCategory;
class NutrientsVariableCategory extends BaseVariableCategory {
	const AMAZON_PRODUCT_CATEGORY = null;
	const BORING = null;
	const CAUSE_ONLY = true;
	const COMBINATION_OPERATION = 'MEAN';
	const COMMON = null;
	const DEFAULT_UNIT_ABBREVIATED_NAME = 'g';
	const DEFAULT_UNIT_ID = 6;
	const DURATION_OF_ACTION = 86400;
	const EFFECT_ONLY = null;
    const FILLING_TYPE = BaseFillingTypeProperty::FILLING_TYPE_NONE;
    const FILLING_VALUE = -1;
	const HELP_TEXT = 'What nutrient do you want to track?';
	const FONT_AWESOME = FontAwesome::NUTRITIONIX;
	const ID = 11;
    const IMAGE_URL = 'https://static.quantimo.do/img/variable_categories/vegetarian_food-96.png';
	const ION_ICON = 'ion-fork';
	const MANUAL_TRACKING = false;
	const MAXIMUM_ALLOWED_VALUE = null;
	const MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE = 'nutrient';
	const MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS = null;
	const MINIMUM_ALLOWED_VALUE = null;
	const MORE_INFO = "Nutrients are compounds in foods essential to life and health, providing us with energy, the building blocks for repair and growth and substances necessary to regulate chemical processes.";
	const NAME = 'Nutrients';
	const ONSET_DELAY = 0;
	const OUTCOME = false;
	const PNG_PATH = 'img/variable_categories/nutrients.png';
    const PNG_URL = 'https://static.quantimo.do/img/variable_categories/nutrients.png';
	const PREDICTOR = true;
	const PUBLIC = true;
	const SETUP_QUESTION = null;
	const STUDY_IMAGE_FILE_NAME = null;
	const SUFFIX = VariableCategoryNameProperty::SUFFIX_INTAKE;
	const SVG_PATH = 'img/variable_categories/nutrients.svg';
    const SVG_URL = 'https://static.quantimo.do/img/variable_categories/nutrients.svg';
	const SYNONYMS = ['Nutrients', 'Nutrient'];
	const VALENCE = null;
	const VARIABLE_CATEGORY_NAME = 'Nutrients';
	const VARIABLE_CATEGORY_NAME_SINGULAR = 'Nutrient';
    public $amazonProductCategory = self::AMAZON_PRODUCT_CATEGORY;
	public $boring = self::BORING;
	public $causeOnly = self::CAUSE_ONLY;
	public $combinationOperation = self::COMBINATION_OPERATION;
	public $common = self::COMMON;
	public $defaultUnitAbbreviatedName = self::DEFAULT_UNIT_ABBREVIATED_NAME;
	public $defaultUnitId = self::DEFAULT_UNIT_ID;
	public $durationOfAction = self::DURATION_OF_ACTION;
	public $effectOnly = self::EFFECT_ONLY;
	public $fillingType = self::FILLING_TYPE;
	public $fillingValue = self::FILLING_VALUE;
	public $helpText = self::HELP_TEXT;
	public $fontAwesome = self::FONT_AWESOME;
	public $id = self::ID;
	public $imageUrl = self::IMAGE_URL;
	public $ionIcon = self::ION_ICON;
	public $manualTracking = self::MANUAL_TRACKING;
	public $maximumAllowedValue = self::MAXIMUM_ALLOWED_VALUE;
	public $measurementSynonymSingularLowercase = self::MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE;
	public $minimumAllowedSecondsBetweenMeasurements = self::MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS;
	public $minimumAllowedValue = self::MINIMUM_ALLOWED_VALUE;
	public $moreInfo = self::MORE_INFO;
	public $name = self::NAME;
	public $onsetDelay = self::ONSET_DELAY;
	public $outcome = self::OUTCOME;
	public $pngPath = self::PNG_PATH;
	public $pngUrl = self::PNG_URL;
	public $predictor = self::PREDICTOR;
	public $public = self::PUBLIC;
	public $setupQuestion = self::SETUP_QUESTION;
	public $studyImageFileName = self::STUDY_IMAGE_FILE_NAME;
	public $suffix = self::SUFFIX;
	public $svgPath = self::SVG_PATH;
	public $svgUrl = self::SVG_URL;
	public $synonyms = self::SYNONYMS;
	public $valence = self::VALENCE;
	public $variableCategoryName = self::VARIABLE_CATEGORY_NAME;
	public $variableCategoryNameSingular = self::VARIABLE_CATEGORY_NAME_SINGULAR;
}
